### ISSUE TITLE
Auxiliary slot

### ISSUE THREAD

**Issue by arvyy** [skinny85/graalvm-truffle-tutorial#3]
> They are stored in something called auxiliary slots; basically a map inside the VirtualFrame. The keys of that map historically were instances of a class called FrameSlot. However, that class has been removed in GraalVM version 22, and now the map is indexed by integers, the same way function arguments are. These integer indexes are related to another important class, FrameDescriptor.

Is the term "auxiliary slot" precise here? I understand the flow with descriptors and eg setObject / getObject methods in the Frame. But it also has methods with literal term "auxiliary" in them: setAuxiliarySlot / getAuxiliarySlot, which seem to be something different and unrelated to frame descriptors.

**Comment by skinny85** [comment]
Hey @arvyy, thanks for opening the issue! You're right, this is not a good term to use anymore. When I originally wrote that paragraph, the tutorial used Truffle in version `21.3.1`, and that version [did not have](https://javadoc.io/static/org.graalvm.truffle/truffle-api/21.3.1/com/oracle/truffle/api/frame/Frame.html) the `getAuxiliarySlot()` / `setAuxiliarySlot()` methods on `VirtualFrame`. However, version `22.3.0`, which we use currently, definitely has them, so I agree it's not no longer wise to use that word.

I'm going to change "auxiliary" to "indexed", which seems to be [currently used vocabulary](https://javadoc.io/static/org.graalvm.truffle/truffle-api/22.3.0/com/oracle/truffle/api/frame/Frame.html#isObject-int-) for these kind of slots.

Let me know if that makes sense!

Thanks,
Adam

**Comment by skinny85** [comment]
Done in https://github.com/skinny85/eol-blog/commit/cba9fccd5897370f10c1cf3064b6d2191c49d626. Thanks again for reporting!
